[MemoryLeak] DCMTKImageReader and INRImageReader
medInria/medInria-public pull request #1119
Opened 2023-04-19 08:50 UTC by mathildemerle

Solve some memory leaks found with valgrind when a user import a data in medInria. In DCMTK reader, fix "new" deletion, and in INR reader fix private class leak.

:m:

2023-09-29 14:01 UTC, fcollot requested changes

2023-10-02 09:15 UTC, mathildemerle commented on src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
> +        m_ptr->unlock();
I removed the changes on mutex (and this file is normally going to be deleted in med4 with https://github.com/medInria/medInria-public/pull/1138 so we'll see later)

2023-10-12 06:42 UTC, fcollot approved these changes

2023-10-12 09:01 UTC, juliencastelneau approved these changes

2023-10-12 09:05 UTC, merged