[VideoExport] add a video export feature: avi, ogv, jpeg
medInria/medInria-public pull request #755
Opened 2020-07-10 10:35 UTC by mathildemerle

This PR adds:
 * Export of **ogv** or **avi** video of a view through **FFMPEG** (Linux and Mac) or **MPEG2** (Windows).
 * Export of a batch of **jpeg** of a view.
 * Kind of export: **rotation** of a mesh.
 * Kind of export: **time** scrolling for a 4D data, with display of the time on the view.
 * Kind of export: **slice** scrolling for a data (for _MUSIC_ devs: it's a new feature, and by the way i switched also ffmpeg from 0.7 to 4.3).
 * The video button is next to the screenshot button, in the bottom bar of the application.

FFMPEG or MPEG2 lib are compiled according to your OS, and are linked to VTK. So, you'll need to recompile from scratch at least VTK in order to test this.

It would be good to test this PR at least on Mac and Windows, since I work on Linux. In MUSIC we did not use fibers/vectors data so, it could be interesting to test some fibers/vector data too.

We had problems with FFMPEG 0.7 with VTK ~5 on Windows, that's why we were using MPEG2 only on Windows. We had also problems with MPEG2 on Linux or Mac haha. That was complicated. It could be solved in VTK 8 or 9, perhaps, I don't know.

Later, it could be interesting to enhance the display of the computation, on Ubuntu 20.04 my cursor does not change when a computation is currently running, only the logs are showing that something is happening. It's a common problem in the application, that's why we added by the way the deactivation of toolboxes during computation. Maybe a message displayed in the current log bar? We'll see that.

:m:

2020-08-27 13:11 UTC, Florent2305 commented
I am embarrassed.

MPEG2 library readme indicates patent and licensing issues.
We also have no redistribution rights (compiled or not) provided by disclaimers of headers of the .h files.

Moreover, ffmpeg depending on its compilation flag can switch from LGPL to GPL, which is not possible. I will investigate this question.

Sincerely sorry. Hope I would find a workaround like only use LGPL part of ffmpeg in any cases.

2020-09-10 13:59 UTC, mathildemerle commented
Update: MPEG2 Writer has been removed from VTK >= 8.2. We were using it on Windows, so, it has been removed too.

2020-09-15 15:01 UTC, Florent2305 commented on src/layers/legacy/medCoreLegacy/CMakeLists.txt
> -  threadpool/threadpoolLight
Oui

2020-09-16 15:46 UTC, mathildemerle commented
I added a commit which:
 * solves a problem with the "if ffmpeg", 
 * adds waiting cursors, 
 * solves a number of step initialize error, 
 * adds a quality parameter to ffmpeg, 
 * switches .avi to .mp4, for ffmpeg,
 * and adds an explanation for users telling them that they can use their own tools for the jpeg or the videos.

2020-09-17 09:13 UTC, Florent2305 requested changes
I made few comments and remarks.
I will test it on Windows

2020-09-17 09:13 UTC, Florent2305 commented on src/plugins/legacy/medExportVideo/medExportVideo.cpp
> +        writerVideoTmp->SetFileName(d->filename.toStdString().c_str());
Be careful with path encoding

2020-09-17 09:13 UTC, Florent2305 commented on src/plugins/legacy/medExportVideo/medExportVideo.cpp
> +    {
Be careful!
What appends if entre in with:

- d->format with other value than FFMPEG
- d->format at FFMPEG but with MED_USE_FFmpeg not define

suggestion:
 
`#ifdef (MED_USE_FFmpeg)`
`        else if (d->format == FFMPEG)`
`        {`
`             vtkSmartPointer<vtkFFMPEGWriter> writerVideoTmp = vtkSmartPointer<vtkFFMPEGWriter>::New();`
`             writerVideoTmp->SetInputConnection(source->GetOutputPort());`
`             writerVideoTmp->SetFileName(d->filename.toStdString().c_str());`
`             writerVideoTmp->SetRate(d->frameRate);`
`             writerVideoTmp->SetQuality(d->quality);`
`             writerVideo = writerVideoTmp;`
`        }`
`#endif`
`        else`
`        {`
`            return medAbstractProcessLegacy::FAILURE;`
`        }`
`    }`

2020-09-17 09:13 UTC, Florent2305 commented on src/plugins/legacy/medExportVideo/medExportVideo.cpp
> +            writerVideoTmp->SetFileName(d->filename.toStdString().c_str());
Be careful with path encoding

2020-09-17 09:13 UTC, Florent2305 commented on src/plugins/legacy/medExportVideo/medExportVideo.cpp
> +#if defined (MED_USE_FFmpeg)
same as previous

2020-09-17 09:13 UTC, Florent2305 commented on src/plugins/legacy/medExportVideo/medExportVideo.h
> +        MPEG2
remove MPEG2

2020-09-17 09:13 UTC, Florent2305 commented on superbuild/projects_modules/VTK.cmake
> +elseif (WIN32)
*you can remove WIN32 Close

2020-09-17 09:51 UTC, Florent2305 approved these changes
Nikel

2020-09-17 11:48 UTC, Florent2305 approved these changes
ok

2020-09-17 14:37 UTC, Florent2305 approved these changes
Ok but not really useful to change DCMTK.cmake and ITK.cmake

2020-09-17 14:52 UTC, mathildemerle commented on superbuild/patches/VTK.patch
> ++  this->outFile = vtksys::SystemTools::Fopen(this->Writer->GetFileName(),"wb");
explanation: we found with @Florent2305 a bug in VTK in vtkOggTheoraWriter on Windows (classic UTF16 problem). There is no problem on vtkJPEGWriter, which uses vtksys::SystemTools::Fopen already. This bug is classic also in other parts of VTK

2020-09-18 12:01 UTC, merged