[PaintToolBox]: fix crash
medInria/medInria-public pull request #792
Opened 2020-11-10 14:21 UTC by paulineMig

fix https://github.com/medInria/medInria-public/issues/790

2020-11-10 14:29 UTC, mathildemerle approved these changes

2020-11-10 15:31 UTC, mjuhoor approved these changes

2020-11-10 16:46 UTC, nebatmusic requested changes
I think the pb is in the caller of this function. 

This is strange ? 
void AlgorithmPaintToolBox::updateStroke(ClickAndMoveEventFilter * filter, medAbstractImageView * view)
{
    setCurrentView(currentView);
....

2020-11-10 17:10 UTC, paulineMig commented
I agree this is really strange (because it put currentView to currentView) but I still had the bug with setCurrentView(view). I will do some more testing and check everything else if nothing is broken i will add the modification.

2020-11-10 17:43 UTC, paulineMig commented
> I think there is also a pb is in the caller of this function.
> 
> This is strange ?
> void AlgorithmPaintToolBox::updateStroke(ClickAndMoveEventFilter * filter, medAbstractImageView * view)
> {
> setCurrentView(currentView);
> if ( !isMask2dOnSlice() )
> {
> return;
> }
> ....
> }
> It seems that is should be setCurrentView(view);

Done

2020-11-12 08:11 UTC, mathildemerle approved these changes

2020-11-12 16:00 UTC, nebatmusic approved these changes

2020-11-13 08:00 UTC, merged