[Package] Mac: do not keep useless Qt plugins
medInria/medInria-public pull request #831
Opened 2021-01-12 14:16 UTC by mathildemerle

Opening the application on mac through a binary, you have error messages with these plugins: bearer, iconengines, imageformats, platforminputcontexts, platforms, printsupport, sqldrivers, styles, virtualkeyboard.
This PR avoids them.

History: it was originally done [here](https://github.com/Inria-Asclepios/medinria-superproject/blob/moreMUSIC/packaging/apple/mac_packager.sh.in).

:m:

2021-01-12 14:56 UTC, Florent2305 commented
Be careful, libraries "_qgif, qicns, qico, qjpeg, qsvg, qtga, qtiff, qwbmp, qwebp, qminimal, qoffscreen, qcocoa, qsqlite_" can be mandatory for non-developer computer.
We need to check, clearly, which libraries contained in these directories cannot be removed.
Even if it means keeping error messages.

2021-01-12 14:56 UTC, Florent2305 requested changes
Check absolutely needed folders

2021-01-12 14:58 UTC, mathildemerle commented
Indeed i'm going to run jenkins during the night on this branch to check

2021-01-12 15:00 UTC, mjuhoor approved these changes

2021-01-12 15:11 UTC, Florent2305 commented
Complementary information see [Apple Doc](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html) at _Table 2-5  Subdirectories of the Contents directory_ line **PlugIns**

2021-03-16 08:30 UTC, mathildemerle commented
I tested a dmg done on this branch, on a fresh macOS (Catalina) VM, and i did not see any problem, i could install, run medInria and open a scene.

2021-03-16 08:56 UTC, fcollot commented
I tested the running application from a dmg and checked which libraries were actually loaded. The platforms, imageformats, styles, sqldrivers and iconengines libraries are being loaded (even though there were error messages related to some of them).
```
IHULMC012-4:MacOS florent.collot$ ps
  PID TTY           TIME CMD
17108 ttys000    0:00.09 -bash
 1085 ttys001    0:01.39 -bash
58863 ttys002    0:00.19 -bash
84306 ttys003    0:01.37 -bash
46774 ttys004    0:00.01 -bash
46859 ttys004    0:02.78 /Volumes/medInria 3.1.1/medInria.app/Contents/MacOS/medInria
46871 ttys005    0:00.09 -bash
IHULMC012-4:MacOS florent.collot$ lsof -p 46859 | grep 'bearer\|iconengines\|imageformats\|platforminputcontexts\|platforms\|printsupport\|sqldrivers\|styles\|virtualkeyboard'
medInria 46859 florent.collot  txt    REG                1,9    1778660       96 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/platforms/libqcocoa.dylib
medInria 46859 florent.collot  txt    REG                1,9      37168      136 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqico.dylib
medInria 46859 florent.collot  txt    REG                1,9      39024      133 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqgif.dylib
medInria 46859 florent.collot  txt    REG                1,9      46248      141 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqicns.dylib
medInria 46859 florent.collot  txt    REG                1,9     214172      118 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/styles/libqmacstyle.dylib
medInria 46859 florent.collot  txt    REG                1,9     427352      138 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqjpeg.dylib
medInria 46859 florent.collot  txt    REG                1,9      37748      137 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqmacheif.dylib
medInria 46859 florent.collot  txt    REG                1,9      37612      143 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
medInria 46859 florent.collot  txt    REG                1,9      32780      140 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqsvg.dylib
medInria 46859 florent.collot  txt    REG                1,9      30436      142 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqtga.dylib
medInria 46859 florent.collot  txt    REG                1,9     437440      139 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqtiff.dylib
medInria 46859 florent.collot  txt    REG                1,9      26980      134 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqwbmp.dylib
medInria 46859 florent.collot  txt    REG                1,9     631356      135 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/imageformats/libqwebp.dylib
medInria 46859 florent.collot  txt    REG                1,9    1576476      130 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/sqldrivers/libqsqlite.dylib
medInria 46859 florent.collot  txt    REG                1,9      47124      127 /Volumes/medInria 3.1.1/medInria.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
IHULMC012-4:MacOS florent.collot$ 
```

2021-03-19 10:21 UTC, mathildemerle commented
Are they loaded because they are in the package, or are they loaded because the are needed? If they are needed, do you know where?

2021-03-19 12:43 UTC, fcollot commented
I built a package with these changes and the plugins are still in the dmg. I manually removed them and the application wouldn't start because it was missing `lbqcocoa`. I put that lib back and medInria started but could not load the database because the sqlite plugin is missing (`libqsqlite`). I put all the libs back and tested the removal of one or two of them like `libqmacstyle`. The application worked, but after a quick google search I found `libqmacstyle` is needed to properly render some UI elements on macOS.
I don't think it's a good idea to remove any of these libs even if the application launches, because they were included by macdeployqt and so are related to the inner workings of Qt that we shouldn't be messing with.

2021-03-19 12:55 UTC, mathildemerle commented
That's weird, because if the qt package were removed before, there is no problem. And in order to explain the background of this PR, it was done on MUSIC ~2 here: https://github.com/Inria-Asclepios/medinria-superproject/blob/moreMUSIC/packaging/apple/mac_packager.sh.in

2021-03-19 13:03 UTC, fcollot commented
The code in the link you point to removes `accessible,bearer,codecs,graphicssystems`, so it's not the same plugins being removed.

2021-03-19 13:05 UTC, fcollot commented
(the libs I'm saying we shouldn't remove are the ones I listed in the output of the `lsof` command)

2021-03-31 07:46 UTC, closed without merging